version: '2'
services:
    nginx:
        build: ./nginx
        ports:
            - 80:80
            - 443:443
        links:
            - php
        volumes:
            - ./xcart:/var/www/xcart

    php:
        build: ./php
        expose:
            - 9000
        links:
            - mariadb
        volumes:
            - ./xcart:/var/www/xcart

    mariadb:
        build: ./mariadb
        expose:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: devpw
            MYSQL_DATABASE: printfirm_com_development
            MYSQL_USER: printfirm_com
            MYSQL_PASSWORD: example_dbpassword
        volumes:
            - /var/lib/mysql
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ./xcart:/var/www/xcart
